#!/usr/bin/env bash
# init.sh — Harness session startup script
# Auto-generated by harness-engineering skill

cd "$(dirname "$0")"
ERRORS=0

echo "=== 1. 环境 ==="
if [ ! -d node_modules ]; then
  echo "安装 pnpm 依赖..."
  corepack pnpm install --frozen-lockfile || {
    echo "⚠️  pnpm install 失败"
    ERRORS=$((ERRORS + 1))
  }
else
  echo "node_modules 已存在，跳过安装。"
fi

echo "=== 2. 基线检查 ==="
corepack pnpm check || {
  echo "⚠️  pnpm check 失败"
  ERRORS=$((ERRORS + 1))
}
corepack pnpm test || {
  echo "⚠️  pnpm test 失败"
  ERRORS=$((ERRORS + 1))
}

echo "=== 3. 启动服务 ==="
mkdir -p output

GATEWAY_HTTP_CODE="$(curl -sS -o /dev/null -w "%{http_code}" http://127.0.0.1:8787/health 2>/dev/null || echo "000")"
if [ "$GATEWAY_HTTP_CODE" = "200" ]; then
  echo "Gateway 已运行。"
else
  echo "启动 Gateway..."
  nohup ./scripts/start-gateway.sh > output/harness-gateway.log 2>&1 &
  sleep 5
fi

WEB_HTTP_CODE="$(curl -sS -o /dev/null -w "%{http_code}" http://127.0.0.1:3000 2>/dev/null || echo "000")"
if [ "$WEB_HTTP_CODE" = "200" ] || [ "$WEB_HTTP_CODE" = "307" ] || [ "$WEB_HTTP_CODE" = "308" ]; then
  echo "Mobile Web 已运行。"
else
  echo "启动 Mobile Web..."
  nohup ./scripts/start-mobile-web.sh > output/harness-web.log 2>&1 &
  sleep 8
fi

echo "=== 4. 健康检查 ==="
GATEWAY_HTTP_CODE="$(curl -sS -o /dev/null -w "%{http_code}" http://127.0.0.1:8787/health 2>/dev/null || echo "000")"
if [ "$GATEWAY_HTTP_CODE" = "200" ]; then
  echo "✅ Gateway /health 正常"
else
  echo "⚠️  Gateway /health 返回 $GATEWAY_HTTP_CODE"
  ERRORS=$((ERRORS + 1))
fi

WEB_HTTP_CODE="$(curl -sS -o /dev/null -w "%{http_code}" http://127.0.0.1:3000 2>/dev/null || echo "000")"
if [ "$WEB_HTTP_CODE" = "200" ] || [ "$WEB_HTTP_CODE" = "307" ] || [ "$WEB_HTTP_CODE" = "308" ]; then
  echo "✅ Mobile Web 入口可访问 ($WEB_HTTP_CODE)"
else
  echo "⚠️  Mobile Web 返回 $WEB_HTTP_CODE"
  ERRORS=$((ERRORS + 1))
fi

echo "=== Init complete (errors: $ERRORS) ==="
exit 0
